settings:
  database:
    host: localhost
    port: 3306
    user: root
    password: root
    database: minecraft
  lock-description:
    coins: "&a价格: 100.0万金币."
    points: "&a价格: 500.0万点券"
    vip: "&a充值 VIP 后自动解锁."
    svp: "&a充值 SVP 后自动解锁."
    mvp: "&a充值 MVP 后自动解锁."