settings:
  database:
    host: 172.18.0.1
    port: 3306
    user: rpg-test
    password: jPGbpbpCy3W5Ssmz
    database: rpg-test
  lock-progress:
    default:
      first:
        description: "&a价格: 0 金币."
        required: "MONEY @ 0.0"
      second:
        description: "&a价格: 100.0万金币."
        required: "MONEY @ 10000000.0"
      third:
        description: "&a价格: 500.0万金币."
        required: "MONEY @ 50000000.0"
    money:
      first:
        description: "&a价格: 1000.0万金币."
        required: "MONEY @ 100000000.0"
      second:
        description: "&a价格: 2500.0万金币."
        required: "MONEY @ 250000000.0"
      third:
        description: "&a价格: 5000.0万金币."
        required: "MONEY @ 500000000.0"
    coins:
      first:
        description: "&a价格: 50.0万点券."
        required: "COINS @ 5000000.0"
      second:
        description: "&a价格: 100.0万点券."
        required: "COINS @ 10000000.0"
      third:
        description: "&a价格: 500.0万点券."
        required: "COINS @ 50000000.0"
    vip:
      first:
        description: "&a开通 VIP 自动解锁"
        required: "POINTS @ 999999999999999.0"
      second:
        description: "&a价格: 100.0万点券."
        required: "COINS @ 10000000.0"
      third:
        description: "&a价格: 500.0万点券."
        required: "COINS @ 20000000.0"
    svp:
      first:
        description: "&a开通 SVP 自动解锁"
        required: "POINTS @ 999999999999999.0"
      second:
        description: "&a价格: 100.0万点券."
        required: "COINS @ 10000000.0"
      third:
        description: "&a价格: 500.0万点券."
        required: "COINS @ 20000000.0"
    mvp:
      first:
        description: "&a开通 MVP 自动解锁"
        required: "POINTS @ 999999999999999.0"
      second:
        description: "&a价格: 100.0万点券."
        required: "COINS @ 10000000.0"
      third:
        description: "&a价格: 500.0万点券."
        required: "COINS @ 20000000.0"